### ISSUE TITLE
Get rid of the unnecessary variable

### ISSUE THREAD

**Issue by foliolo** [Steampunk1453/todo-task-manager-android#31]
https://github.com/Steampunk1453/todo-task-manager-android/blob/5228d0ffc2cd7fc8e373c721170029f4797d4e5d/app/src/main/java/org/task/manager/data/network/source/AccountDataSource.kt#L14

Why don't you do that right away: 
```
    suspend fun register(request: RegisterRequest) =
        dataSourceProvider.getAccountDataSource().apply {
            register(request)
        }
```

**Comment by Steampunk1453** [comment]
Because for me me the code is more clear if you divide the logic of the method in two lines. First, you get the data source and second, you register the request. it's just for clarity, but it's more code. It's true, your proposal is totally valid. Thanks for your comment.

**Comment by Steampunk1453** [comment]
> https://github.com/Steampunk1453/todo-task-manager-android/blob/5228d0ffc2cd7fc8e373c721170029f4797d4e5d/app/src/main/java/org/task/manager/data/network/source/AccountDataSource.kt#L14
> 
> Why don't you do that right away:
> 
> ```
>     suspend fun register(request: RegisterRequest) =
>         dataSourceProvider.getAccountDataSource().apply {
>             register(request)
>         }
> ```



> https://github.com/Steampunk1453/todo-task-manager-android/blob/5228d0ffc2cd7fc8e373c721170029f4797d4e5d/app/src/main/java/org/task/manager/data/network/source/AccountDataSource.kt#L14
> 
> Why don't you do that right away:
> 
> ```
>     suspend fun register(request: RegisterRequest) =
>         dataSourceProvider.getAccountDataSource().apply {
>             register(request)
>         }
> ```
Because for me me the code is more clear if you divide the logic of the method in two lines. First, you get the data source and second, you register the request. it's just for clarity, but it's more code. It's true, your proposal is totally valid. Thanks for your comment.
